language: node_js

node_js:
 - "4"
 - "6"
 - "8"
 - "10"

branches:
  only:
    - master

services:
 - mongodb

install:
 - npm install

before_install:
 - npm update -q
 - npm install -g grunt-cli

dist: precise

